# .github/workflows/my-project.yml
name: PPAC

on:
  pull_request: 
    branches: [ develop ]
  push:
    branches: [ infra/discord-webhook-설정 ]

jobs:
  build:
    name: test action
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3

    - name: Access Available
      run: chmod +x Scripts/onboarding.sh
    
    - name: Install Setup Script and Fetch Dependencies
      run: ./Scripts/onboarding.sh

    - name: Source bashrc
      shell: bash -l {0}
      run: source ~/.bashrc && mise doctor

    - name: Install tuist
      shell: bash -l {0}
      run: mise install

    - name: Install dependencies
      shell: bash -l {0}
      run: mise exec -- tuist install

    - name: Build and Test
      id: build_and_test
      shell: bash -l {0}
      run: mise exec -- tuist test PPACIOS-Workspace

    - name: Notify Discord on Success
      if: ${{ success() }}
      uses: ilovepotatoes/actions-for-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        message: "✅ Tests passed for PR: ${{ github.event.pull_request.title }}. PR URL: ${{ github.event.pull_request.html_url }}"

    - name: Notify Discord on Failure
      if: ${{ failure() }}
      uses: ilovepotatoes/actions-for-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        message: "❌ Tests failed for PR: ${{ github.event.pull_request.title }}. PR URL: ${{ github.event.pull_request.html_url }}"
